#Parameters for husky bag file recorded by me

lidar_config_file: "/home/zzz/ros/hdl64.cfg"

node: {
  fixed_frame: "map",
  cloud_frame_id: "front_laser",
  topic_clouds: "/front/scan/cloud",
  num_thread: 1
}

clusterer: {
  angle_tollerance: 10,
  min_cluster_size: 5,
  max_cluster_size: 800
}

cloud_publisher: {
  topic_name: "segmented_cloud"
}

objects_publisher: {
  topic_name: "segmented_objects",
  use_axial_bounding_box: true,
  frame_id: "front_laser" # work on tf. otherwise it cant be different from node frame
}


